language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
install: true

script:
- export CC=gcc-7
- export CXX=g++-7
- mkdir bin
- cd bin
- cmake ../
- make
- cd ../
- ./bin/test/emulator_test/emulator_test