language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - libsdl2-2.0-0
      - libsdl2-dev
      - libsdl2-gfx-dev
      - libsdl2-image-2.0-0
      - libsdl2-image-dev
install: true

script:
- export CC=gcc-7
- export CXX=g++-7
- mkdir bin
- cd bin
- cmake ../
- make
- cd ../
- ./bin/test/emulator_test/emulator_test