#include "TestCpuHelpers.h"

#include <sstream>
#include <iomanip>

using namespace std;
using namespace Emulator::Memory;
using namespace Emulator::Cpu;

std::string parseCurrentStateLog(const Emulator::Memory::Memory& memory, const Emulator::Cpu::Registers& registers)
{
    stringstream sstream;
    sstream << hex << registers.getProgramCounter() << " ";
    
    switch (registers.getProgramCounter())
    {
        case 0x69: sstream << "0x69 " << hex << memory.getFrom(registers.getProgramCounter() +1); break; 
        case 0x65: sstream << "0x65 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x75: sstream << "0x75 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x6D: sstream << "0x6D " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x7D: sstream << "0x7D " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x79: sstream << "0x79 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x61: sstream << "0x61 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x71: sstream << "0x71 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x29: sstream << "0x29 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x25: sstream << "0x25 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x35: sstream << "0x35 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x2D: sstream << "0x2D " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x3D: sstream << "0x3D " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x39: sstream << "0x39 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x21: sstream << "0x21 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x31: sstream << "0x31 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x0A: sstream << "0x0A "; break; 
        case 0x06: sstream << "0x06 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x16: sstream << "0x16 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x0E: sstream << "0x0E " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x1E: sstream << "0x1E " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x90: sstream << "0x90 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xB0: sstream << "0xB0 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xF0: sstream << "0xF0 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x24: sstream << "0x24 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x2C: sstream << "0x2C " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x30: sstream << "0x30 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xD0: sstream << "0xD0 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x10: sstream << "0x10 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x50: sstream << "0x50 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x70: sstream << "0x70 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xC6: sstream << "0xC6 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xD6: sstream << "0xD6 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xCE: sstream << "0xCE " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xDE: sstream << "0xDE " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xCA: sstream << "0xCA "; break; 
        case 0x88: sstream << "0x88 "; break; 
        case 0xE6: sstream << "0xE6 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xF6: sstream << "0xF6 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xEE: sstream << "0xEE " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xFE: sstream << "0xFE " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xE8: sstream << "0xE8 "; break; 
        case 0xC8: sstream << "0xC8 "; break; 
        case 0xA9: sstream << "0xA9 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xA5: sstream << "0xA5 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xB5: sstream << "0xB5 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xAD: sstream << "0xAD " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xBD: sstream << "0xBD " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xB9: sstream << "0xB9 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xA1: sstream << "0xA1 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xB1: sstream << "0xB1 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xA2: sstream << "0xA2 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xA6: sstream << "0xA6 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xB6: sstream << "0xB6 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xAE: sstream << "0xAE " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xBE: sstream << "0xBE " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xA0: sstream << "0xA0 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xA4: sstream << "0xA4 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xB4: sstream << "0xB4 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xAC: sstream << "0xAC " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xBC: sstream << "0xBC " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x48: sstream << "0x48 "; break; 
        case 0x68: sstream << "0x68 "; break; 
        case 0x08: sstream << "0x08 "; break; 
        case 0x28: sstream << "0x28 "; break; 
        case 0x38: sstream << "0x38 "; break; 
        case 0xF8: sstream << "0xf8 "; break; 
        case 0x78: sstream << "0x78 "; break; 
        case 0x18: sstream << "0x18 "; break; 
        case 0xD8: sstream << "0xd8 "; break; 
        case 0x58: sstream << "0x58 "; break; 
        case 0xB8: sstream << "0xb8 "; break; 
        case 0xAA: sstream << "0xAA "; break; 
        case 0xBA: sstream << "0xBA "; break; 
        case 0x8A: sstream << "0x8A "; break; 
        case 0x9A: sstream << "0x9A "; break; 
        case 0x98: sstream << "0x98 "; break; 
        case 0x4C: sstream << "0x4C " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x6C: sstream << "0x6C " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xE9: sstream << "0xE9 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xE5: sstream << "0xE5 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xF5: sstream << "0xF5 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xED: sstream << "0xED " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xFD: sstream << "0xFD " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xF9: sstream << "0xF9 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xE1: sstream << "0xE1 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xF1: sstream << "0xF1 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x85: sstream << "0x85 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x8D: sstream << "0x8D " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x9D: sstream << "0x9D " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x99: sstream << "0x99 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x81: sstream << "0x81 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x91: sstream << "0x91 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x86: sstream << "0x86 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x96: sstream << "0x96 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x8E: sstream << "0x8E " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x84: sstream << "0x84 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x94: sstream << "0x94 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x8C: sstream << "0x8C " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xEA: sstream << "0xEA "; break; 
        case 0x2A: sstream << "0x2A "; break; 
        case 0x26: sstream << "0x26 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x36: sstream << "0x36 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x2E: sstream << "0x2E " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x3E: sstream << "0x3E " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x6A: sstream << "0x6A "; break; 
        case 0x66: sstream << "0x66 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x76: sstream << "0x76 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x6E: sstream << "0x6E " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x7E: sstream << "0x7E " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x4A: sstream << "0x4A "; break; 
        case 0x46: sstream << "0x46 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x56: sstream << "0x56 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x4E: sstream << "0x4E " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x5E: sstream << "0x5E " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xC9: sstream << "0xC9 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xC5: sstream << "0xC5 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xD5: sstream << "0xD5 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xCD: sstream << "0xCD " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xDD: sstream << "0xDD " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xD9: sstream << "0xD9 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xC1: sstream << "0xC1 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xD1: sstream << "0xD1 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xE0: sstream << "0xE0 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xE4: sstream << "0xE4 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xEC: sstream << "0xEC " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0xC0: sstream << "0xC0 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xC4: sstream << "0xC4 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0xCC: sstream << "0xCC " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x49: sstream << "0x49 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x45: sstream << "0x45 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x55: sstream << "0x55 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x4D: sstream << "0x4D " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x5D: sstream << "0x5D " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x59: sstream << "0x59 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x41: sstream << "0x41 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x51: sstream << "0x51 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x09: sstream << "0x09 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x05: sstream << "0x05 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x15: sstream << "0x15 " << hex << memory.getFrom(registers.getProgramCounter() +1); break;
        case 0x0D: sstream << "0x0D " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x1D: sstream << "0x1D " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x19: sstream << "0x19 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x01: sstream << "0x01 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x11: sstream << "0x11 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x20: sstream << "0x20 " << hex << memory.getFrom(registers.getProgramCounter() +1) << " " << hex << memory.getFrom(registers.getProgramCounter() +2); break;
        case 0x60: sstream << "0x60 "; break; 
        case 0x40: sstream << "0x40 "; break; 
        case 0x00: sstream << "0x00 "; break; 
    }

    sstream << "A:" << hex << registers.getAccumulator();
    sstream << "Y:" << hex << registers.getIndexRegisterX();
    sstream << "X:" << hex << registers.getIndexRegisterY();
    sstream << "P:" << hex << registers.getStatusFlags();
    sstream << "SP:" << hex << registers.getStackPointerOffset();

    return sstream.str();
}
